# ClientBrand
CLIENT_BRAND: munro
STORE_CODE: AU-MUNRO001

# Initial
PORT: 5501
NODE_ENV: dev
HOST: localhost


#EXECUTION_TASKS:
#  runProcessFiles: true
#  tasks:
#    - processFiles
#    - appendToFile
#    - moveToArchive
#  runZipAndMove: true
#  runEmptyTheDirectory: true
  # Or alternatively for another valid configuration:
  # - saveToDatabase
  # - moveToArchive
  # - runZipAndMove


# PATH_CONFIG section
PATH_CONFIG:
  isEnabled: true # Set to true to enable the application operations
  sourceZipDirectory: C:\projects\hendricks\experiment\event-traffic-mock-data\backup
  destinationZipDirectory: C:\projects\hendricks\experiment\event-traffic-mock-data\zippedArchive
  miscErrorDirectory: C:\projects\hendricks\experiment\event-traffic-mock-data\miscError
  dbInsertionErrorDirectory: C:\projects\hendricks\experiment\event-traffic-mock-data\dbInsertionError
  fieldConfigErrorDirectory: C:\projects\hendricks\experiment\event-traffic-mock-data\fieldConfigError
  winstonLogDirectory: ../logs/backup-service
#  appendToFile: D:\davidho\tools\event-traffic-mock-data\appendToFile

  # Option to execute the following tasks
  runProcessFiles: true
  runZipAndMove: true
  runEmptyTheDirectory: true
#  runZipAndMove: true
#  runEmptyTheDirectory: true

  # Set either dailyAt or everyXHours or everyXMinutes.
  dailyAt: null  # Example: Run daily at 13:16.
  everyXHours: null # Example: Run every 3 hours.
  everyXMinutes: 1  # Example: Run every 15 minutes
  BATCH_SIZE: 10

  # runProcessFiles must be set to true to run the following tasks
  # FILE_FIELD_MAP
  FILE_FIELD_MAP:
    capacity:
      spacing: 4
      validate: 12
      fields:
        - date_time
        - store_code
        - detection_id
        - tracker_id
        - event_type
        - event_name
        - region
        - class_type
        - camera_name
        - count
        - message
        - region_id
        - zone_name
    dwell:
      spacing: 3
      validate: 12
      fields:
        - date_time
        - store_code
        - detection_id
        - tracker_id
        - event_name
        - event_type
        - duration
        - class_type
        - camera_name
        - region
        - message
        - region_id
        - zone_name

# runProcessFiles must be set to true to run the following tasks
# DB SCHEMA MAPPING
DB_SCHEMA:
  name: Detection
  fields:
    - name: id
      type: Int
      isId: true
    - name: detection_id
      type: String
    - name: tracker_id
      type: String
    - name: store_code
      type: String
    - name: event_type
      type: String
    - name: event_name
      type: String
    - name: duration
      type: Float
      default: "0"
    - name: count
      type: Int
      default: "0"
    - name: class_type
      type: String
    - name: message
      type: String
    - name: date_time
      type: DateTime
    - name: camera_name
      type: String
    - name: region
      type: String
    - name: region_id
      type: String
    - name: zone_name
      type: String
    - name: file_name
      type: String
      nullable: true