# ClientBrand
CLIENT_BRAND: munro
STORE_CODE: AU-MUNRO001

# Initial
PORT: 5501
NODE_ENV: dev
BATCH_SIZE: 500
HOST: localhost

# PATH
PATH_CONFIG:
  isEnabled: true
  folderToZip: C:\projects\hendricks\experiment\event-traffic-mock-data\backup
  destinationPath: C:\projects\hendricks\experiment\event-traffic-mock-data\archived
  scheduledTime: 11:57